### ISSUE TITLE
Exception in DefaultResponseErrorHandler.java line 91

### ISSUE THREAD

**Issue by ironjan** [ironjan/metal-only#161]
http://crashes.to/s/7a2c65e3b73

63 CRASHES
12 USERS

motorola 46%
samsung 46%
huawei 8%

Operating Systems
7 74%
6 16%
4 5%
5 5%

```
# Crashlytics - plaintext stacktrace downloaded by Jan Lippert at Fri, 01 Dec 2017 11:33:14 GMT
# URL: https://fabric.io/none11111111111501931217/android/apps/com.codingspezis.android.metalonly.player/issues/5a20b2d461b02d480d9e9275?time=last-seven-days/sessions/5A20EDED03DE000114DFF858B330A034_c083ca8ed65b11e7844356847afe9799_0_v2
# Organization: None
# Platform: android
# Application: Metal Only
# Version: 0.6.14 (61400)
# Bundle Identifier: com.codingspezis.android.metalonly.player
# Issue #: 8
# Issue ID: 5a20b2d461b02d480d9e9275
# Session ID: 5A20EDED03DE000114DFF858B330A034_c083ca8ed65b11e7844356847afe9799_0_v2
# Date: 2017-12-01T05:51:00Z
# OS Version: 4.3
# Device: Y530
# RAM Free: 14.7%
# Disk Free: 9.5%

#0. Crashed: Thread-500: 0 0 0x0000000000000000
       at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
       at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:585)
       at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:541)
       at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:499)
       at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:447)
       at com.github.ironjan.metalonly.client_library.MetalOnlyAPI_.getStats(MetalOnlyAPI_.java:49)
       at com.github.ironjan.metalonly.client_library.MetalOnlyClientImplementation.getStats(MetalOnlyClientImplementation.kt:55)
       at com.codingspezis.android.metalonly.player.StreamControlActivity$1.run(StreamControlActivity.java:178)
       at java.lang.Thread.run(Thread.java:841)

--

Fatal Exception: org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
       at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
       at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:585)
       at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:541)
       at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:499)
       at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:447)
       at com.github.ironjan.metalonly.client_library.MetalOnlyAPI_.getStats(MetalOnlyAPI_.java:49)
       at com.github.ironjan.metalonly.client_library.MetalOnlyClientImplementation.getStats(MetalOnlyClientImplementation.kt:55)
       at com.codingspezis.android.metalonly.player.StreamControlActivity$1.run(StreamControlActivity.java:178)
       at java.lang.Thread.run(Thread.java:841)

#0. Crashed: Thread-500: 0 0 0x0000000000000000
       at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
       at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:585)
       at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:541)
       at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:499)
       at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:447)
       at com.github.ironjan.metalonly.client_library.MetalOnlyAPI_.getStats(MetalOnlyAPI_.java:49)
       at com.github.ironjan.metalonly.client_library.MetalOnlyClientImplementation.getStats(MetalOnlyClientImplementation.kt:55)
       at com.codingspezis.android.metalonly.player.StreamControlActivity$1.run(StreamControlActivity.java:178)
       at java.lang.Thread.run(Thread.java:841)

#1. pool-4-thread-1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2019)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1013)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1073)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)

#2. FinalizerDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:401)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:102)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:73)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
       at java.lang.Thread.run(Thread.java:841)

#3. Crashlytics Report Uploader
       at java.lang.VMThread.sleep(VMThread.java)
       at java.lang.Thread.sleep(Thread.java:1013)
       at java.lang.Thread.sleep(Thread.java:995)
       at com.crashlytics.android.core.ReportUploader$Worker.attemptUploadWithRetry(ReportUploader.java:188)
       at com.crashlytics.android.core.ReportUploader$Worker.onRun(ReportUploader.java:173)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:841)

#4. pool-1-thread-1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2019)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1052)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:780)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1013)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1073)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)

#5. Binder_1
       at dalvik.system.NativeStart.run(NativeStart.java)

#6. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2019)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:505)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1013)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1073)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)

#7. FinalizerWatchdogDaemon
       at java.lang.VMThread.sleep(VMThread.java)
       at java.lang.Thread.sleep(Thread.java:1013)
       at java.lang.Thread.sleep(Thread.java:995)
       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:248)
       at java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:258)
       at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:212)
       at java.lang.Thread.run(Thread.java:841)

#8. Answers Events Handler1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:199)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2058)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1063)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:780)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1013)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1073)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:841)

#9. Signal Catcher
       at dalvik.system.NativeStart.run(NativeStart.java)

#10. ReferenceQueueDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:364)
       at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:130)
       at java.lang.Thread.run(Thread.java:841)

#11. Crashlytics Exception Handler1
       at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
       at java.lang.Thread.getStackTrace(Thread.java:579)
       at java.lang.Thread.getAllStackTraces(Thread.java:521)
       at com.crashlytics.android.core.CrashlyticsController.writeSessionEvent(CrashlyticsController.java:1114)
       at com.crashlytics.android.core.CrashlyticsController.writeFatal(CrashlyticsController.java:852)
       at com.crashlytics.android.core.CrashlyticsController.access$400(CrashlyticsController.java:59)
       at com.crashlytics.android.core.CrashlyticsController$6.call(CrashlyticsController.java:292)
       at com.crashlytics.android.core.CrashlyticsController$6.call(CrashlyticsController.java:285)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:841)

#12. GC
       at dalvik.system.NativeStart.run(NativeStart.java)

#13. main
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:132)
       at android.os.Looper.loop(Looper.java:124)
       at android.app.ActivityThread.main(ActivityThread.java:5457)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:854)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:670)
       at dalvik.system.NativeStart.main(NativeStart.java)

#14. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2019)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:505)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1013)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1073)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)

#15. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2019)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:505)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get(DependencyPriorityBlockingQueue.java:236)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:65)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:46)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1013)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1073)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)

#16. Binder_2
       at dalvik.system.NativeStart.run(NativeStart.java)

#17. Thread-500
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)
       at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:396)
       at java.util.concurrent.FutureTask.get(FutureTask.java:159)
       at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:43)
       at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:285)
       at com.crashlytics.android.core.CrashlyticsController$5.onUncaughtException(CrashlyticsController.java:269)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:30)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

```

**Comment by ironjan** [comment]
Only affects 0.6.14 and is already fixed - problem occurs because users don't update -.-
