### ISSUE TITLE
Crash because of java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by ironjan** [ironjan/metal-only#5]
Could have ben introduced in version 0.4.16
Stacktrace:
```
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{11192e55 V.E..... R......D 0,0-1368,389} not attached to window manager
    at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:412)
    at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:338)
    at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:118)
    at android.app.Dialog.dismissDialog(Dialog.java:522)
    at android.app.Dialog.dismiss(Dialog.java:504)
    at com.codingspezis.android.metalonly.player.siteparser.HTTPGrabber$3.run(HTTPGrabber.java:170)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6872)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by ironjan** [comment]
Only occured once. Could not be reproduced since then.
