### ISSUE TITLE
IllegalStateException reported via Google Play

### ISSUE THREAD

**Issue by ironjan** [ironjan/metal-only#70]
60100	11x
60000	7x

No crashes in newer versions.

```
java.lang.IllegalStateException: 
  at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
  at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
  at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:649)
  at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
  at com.codingspezis.android.metalonly.player.PlanActivity.onPlanLoaded(PlanActivity.java:115)
  at com.codingspezis.android.metalonly.player.PlanActivity_.access$101(PlanActivity_.java:34)
  at com.codingspezis.android.metalonly.player.PlanActivity_$2.run(PlanActivity_.java:122)
  at android.os.Handler.handleCallback(Handler.java:733)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5336)
  at java.lang.reflect.Method.invokeNative(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
  at dalvik.system.NativeStart.main(Native Method:0)
```

**Comment by ironjan** [comment]
Duplicate of #71
