### ISSUE TITLE
IllegalStateException introduced in 0.6.3

### ISSUE THREAD

**Issue by ironjan** [ironjan/metal-only#71]
```
java.lang.IllegalStateException: 
  at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1864)
  at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:649)
  at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:614)
  at com.codingspezis.android.metalonly.player.PlanActivity.onPlanLoaded(PlanActivity.java:105)
  at com.codingspezis.android.metalonly.player.PlanActivity_.access$101(PlanActivity_.java:34)
  at com.codingspezis.android.metalonly.player.PlanActivity_$2.run(PlanActivity_.java:121)
  at android.os.Handler.handleCallback(Handler.java:761)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:156)
  at android.app.ActivityThread.main(ActivityThread.java:6523)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

**Comment by ironjan** [comment]
False positive. According to Dev Console this issue was introduced in 0.6.3 - however, `PlanActivity` does not have any fragment transactions in 0.6.3+.
