### ISSUE TITLE
NetworkOnMainThread (1) introduced in 0.6.3(?)

### ISSUE THREAD

**Issue by ironjan** [ironjan/metal-only#73]
```
android.os.NetworkOnMainThreadException: 
  at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
  at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1169)
  at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1164)
  at com.android.okhttp.Connection.closeIfOwnedBy(Connection.java:1175)
  at com.android.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:126)
  at com.android.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:313)
  at com.android.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:566)
  at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:119)
  at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.disconnect(DelegatingHttpsURLConnection.java:93)
  at com.android.okhttp.internal.http.HttpsURLConnectionImpl.disconnect(HttpsURLConnectionImpl.java:25)
  at org.springframework.http.client.SimpleClientHttpResponse.closeInternal(SimpleClientHttpResponse.java:120)
  at org.springframework.http.client.AbstractClientHttpResponse.close(AbstractClientHttpResponse.java:57)
  at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:495)
  at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:439)
  at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:415)
  at com.codingspezis.android.metalonly.player.utils.jsonapi.MetalOnlyAPI_.getStats(MetalOnlyAPI_.java:49)
  at com.codingspezis.android.metalonly.player.utils.jsonapi.MetalOnlyAPIWrapper.getStats(MetalOnlyAPIWrapper.java:80)
  at com.codingspezis.android.metalonly.player.fragments.FavoritesFragment.wishSong(FavoritesFragment.java:171)
  at com.codingspezis.android.metalonly.player.fragments.FavoritesFragment.handleAction(FavoritesFragment.java:153)
  at com.codingspezis.android.metalonly.player.fragments.FavoritesFragment.access$200(FavoritesFragment.java:46)
  at com.codingspezis.android.metalonly.player.fragments.FavoritesFragment$2.onClick(FavoritesFragment.java:236)
  at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1157)
  at android.widget.AdapterView.performItemClick(AdapterView.java:339)
  at android.widget.AbsListView.performItemClick(AbsListView.java:1534)
  at android.widget.AbsListView$PerformClick.run(AbsListView.java:3708)
  at android.widget.AbsListView$3.run(AbsListView.java:5692)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:145)
  at android.app.ActivityThread.main(ActivityThread.java:6838)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

```

**Comment by ironjan** [comment]
Same cause as #75: `com.codingspezis.android.metalonly.player.favorites.FavoritesFragment.wishSong(FavoritesFragment.java:168)`
