### ISSUE TITLE
NetworkOnMainThreadException - since 0.5.0

### ISSUE THREAD

**Issue by ironjan** [ironjan/metal-only#74]
60100	6	31,6 %
60000	5	26,3 %
60400 BETA	4	21,1 %
50000	4	21,1 %

```
android.os.NetworkOnMainThreadException: 
  at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
  at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:300)
  at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1194)
  at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1189)
  at com.android.okhttp.Connection.closeIfOwnedBy(Connection.java:148)
  at com.android.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:77)
  at com.android.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:137)
  at com.android.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:135)
  at com.android.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:573)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:134)
  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.disconnect(DelegatingHttpsURLConnection.java:93)
  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.disconnect(HttpsURLConnectionImpl.java:0)
  at org.springframework.http.client.SimpleClientHttpResponse.closeInternal(SimpleClientHttpResponse.java:120)
  at org.springframework.http.client.AbstractClientHttpResponse.close(AbstractClientHttpResponse.java:57)
  at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:495)
  at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:439)
  at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:415)
  at com.codingspezis.android.metalonly.player.utils.jsonapi.MetalOnlyAPI_.getStats(MetalOnlyAPI_.java:49)
  at com.codingspezis.android.metalonly.player.utils.jsonapi.MetalOnlyAPIWrapper.getStats(MetalOnlyAPIWrapper.java:75)
  at com.codingspezis.android.metalonly.player.favorites.FavoritesFragment.wishSong(FavoritesFragment.java:168)
  at com.codingspezis.android.metalonly.player.favorites.FavoritesFragment.handleAction(FavoritesFragment.java:150)
  at com.codingspezis.android.metalonly.player.favorites.FavoritesFragment.access$200(FavoritesFragment.java:43)
  at com.codingspezis.android.metalonly.player.favorites.FavoritesFragment$2.onClick(FavoritesFragment.java:233)
  at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1119)
  at android.widget.AdapterView.performItemClick(AdapterView.java:310)
  at android.widget.AbsListView.performItemClick(AbsListView.java:1229)
  at android.widget.AbsListView$PerformClick.run(AbsListView.java:3234)
  at android.widget.AbsListView$3.run(AbsListView.java:4153)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:173)
  at android.app.ActivityThread.main(ActivityThread.java:6459)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
```

**Comment by ironjan** [comment]
Same cause as #75 
```
  at com.codingspezis.android.metalonly.player.favorites.FavoritesFragment.wishSong(FavoritesFragment.java:168)
```
